hive/models.py
from datetime import datetime, timedelta, timezone

from flask_login import UserMixin
from sqlalchemy import String, Text
from sqlalchemy.orm import Mapped, mapped_column

from hive.core.extensions import bcrypt, db


class Message(db.Model):
    id: Mapped[int] = mapped_column(primary_key=True)
    name: Mapped[str] = mapped_column(String(30))
    body: Mapped[str] = mapped_column(Text)
    created_at: Mapped[datetime] = mapped_column(default= lambda: datetime.now(timezone.utc), index=True)

    def time_since_creation(self) -> timedelta:
        created_at_tz_aware = self.created_at.replace(tzinfo=timezone.utc)
        now = datetime.now(timezone.utc)
        td = now - created_at_tz_aware
        return td

class User(db.Model, UserMixin):
    id: Mapped[int] = mapped_column(primary_key=True)
    username: Mapped[str] = mapped_column(String(30), unique=True, nullable=False)
    password: Mapped[str] = mapped_column(String(128)) 
    
    def set_password(self, password):
        self.password = bcrypt.generate_password_hash(password)

    def set_profile_picture(self, path):
        self.profile_picture = path
    
    def validate_password(self, input_password):
        return bcrypt.check_password_hash(self.password, input_password)
    
    def to_dict(self):
        return {
            "id": self.id,
            "username": self.username,
        }
    

hive/forms.py
from flask_wtf import FlaskForm
from wtforms import PasswordField, StringField, SubmitField, TextAreaField
from wtforms.validators import DataRequired, EqualTo, Length


class PostMessageForm(FlaskForm):
    name = StringField('Name', validators=[DataRequired()], render_kw={"placeholder": 'Enter your name...'})
    body = TextAreaField('Message', validators=[DataRequired()], render_kw={"placeholder": 'Enter a message...'})
    submit = SubmitField()

class LoginForm(FlaskForm):
    username = StringField('Username', validators=[DataRequired()])
    password = PasswordField('Password', validators=[DataRequired()])
    submit = SubmitField('Login')
    
class SignupForm(FlaskForm):
    username = StringField('Username', validators=[DataRequired(), Length(5,20, message="Username must be between 3 and 20 characters")])
    password = PasswordField('Password', validators=[DataRequired(), Length(min=3, message="Password must be at least 3 characters long.")])
    confirm_password = PasswordField('Confirm Password', validators=[
        DataRequired(message="Password confirmation is required."), 
        EqualTo('password', message="Passwords must match."),])
    submit = SubmitField('Signup')
    

hive/__init__.py
import os
import sys
from math import ceil

import humanize
from dotenv import load_dotenv
from flask import Flask

from hive.blueprints.auth import auth_bp
from hive.blueprints.main import main_bp
from hive.blueprints.message import message_bp
from hive.config import DevelopmentConfig, ProductionConfig, TestingConfig
from hive.core.commands import register_commands
from hive.core.errors import register_errors
from hive.core.extensions import bcrypt, crsf, db, limiter, login_manager, migrate
from hive.models import Message, User

# Load environment variables
load_dotenv()

WIN = sys.platform.startswith('win')

def create_app(config_class=None):
    app = Flask(__name__)

    # Config selection
    if config_class is not None:
        config = config_class
        app.config.from_object(config_class)
    else:
        env = os.getenv("FLASK_CONFIG", "development")

        config_map = {
            "development": DevelopmentConfig,
            "testing": TestingConfig,
            "production": ProductionConfig,
        }

        config = config_map[env]
        app.config.from_object(config)

    # Bind extensions to app
    db.init_app(app)
    limiter.init_app(app)
    bcrypt.init_app(app)
    crsf.init_app(app)
    login_manager.init_app(app)
    migrate.init_app(app, db)

    print(f'DB is: {app.config["SQLALCHEMY_DATABASE_URI"]}')

    # Import and register blueprints
    app.register_blueprint(main_bp)
    app.register_blueprint(auth_bp)
    app.register_blueprint(message_bp)

    register_commands(app)
    register_errors(app)

    @app.context_processor
    def utility_processor():
        def get_timedelta_string(message: Message):
            td = message.time_since_creation()
            return humanize.naturaldelta(td)
        def count_pages():
            stmnt = db.select(Message)
            result = db.session.execute(stmnt).scalars().all()
            return int(ceil(len(result)/100))
        return dict(get_timedelta_string=get_timedelta_string, count_pages=count_pages)
    
    return app

@login_manager.user_loader
def load_user(user_id):
    user = db.session.execute(db.select(User).where(User.id == user_id)).scalars().first()
    return user

hive/blueprints/auth.py
from flask import Blueprint, flash, redirect, render_template, url_for
from flask_login import login_required, login_user, logout_user

from hive.core.extensions import db
from hive.forms import LoginForm, SignupForm
from hive.models import User

auth_bp = Blueprint('auth', __name__)

@auth_bp.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        username = form.username.data.strip()
        password = form.password.data.strip()
        user: User = db.session.execute(db.select(User).where(User.username == username)).scalars().first()
        if user and user.validate_password(password):
            login_user(user)
            flash(f'Successfully signed in, welcome {username}', 'success')        
            return redirect(url_for('main.index'))
        flash('User not found or password was incorrect, try again.', 'error')        
        return redirect(url_for('auth.login'))    
    return render_template('login.html', form=form)

@auth_bp.route('/signup', methods=['GET', 'POST'])
def signup():
    form = SignupForm()
    if form.validate_on_submit():
        username = form.username.data.strip()
        password = form.password.data.strip()
        exists = db.session.execute(db.select(User).where(User.username == username)).scalars().first()
        
        if not exists:
            user = User(username=username)
            user.set_password(password)
            db.session.add(user)
            db.session.commit()
            flash('User successfully created! Please sign in.', 'success')        
            return redirect(url_for('auth.login'))
        else:
            flash('User already exists, please use a different username.', 'error')     
            return redirect(url_for('auth.signup'))
    return render_template('signup.html', form=form)

@auth_bp.route('/logout')
@login_required
def logout():
    logout_user()
    flash('Goodbye!')
    return redirect(url_for('auth.login'))

hive/blueprints/main.py
from flask import Blueprint, render_template

from hive.core.extensions import db
from hive.forms import PostMessageForm
from hive.models import Message

main_bp = Blueprint('main', __name__)

@main_bp.route('/')
def index():
    form = PostMessageForm()
    page = db.paginate(db.select(Message).order_by(Message.created_at.desc()), per_page=100)
    return render_template("index.html", page=page, form=form)

hive/blueprints/message.py
from flask import Blueprint, flash, redirect, request, url_for

from hive.core.extensions import db, limiter
from hive.forms import PostMessageForm
from hive.models import Message

message_bp = Blueprint('message', __name__, url_prefix='/message')

@message_bp.route('/post', methods=['POST'])
@limiter.limit("20 per hour")
def post_message():
    form = PostMessageForm()

    if form.validate_on_submit():
        name = request.form.get('name').strip()
        body = request.form.get('body').strip()
        message = Message(name=name, body=body)
        db.session.add(message)
        db.session.commit()
        flash("Message succesfully added!", "success")
        return(redirect(url_for('main.index')))
    
    flash(f"Error in message {form.errors.items()}", 'warning')
    return redirect(url_for('main.index'))

hive/templates/base.html
{% set current_page = request.endpoint %}
{% import 'macros.html' as macros %}

{% block doc -%}
<!DOCTYPE html>
<html {% block html_attribs %} data-bs-theme='dark' {% endblock html_attribs %}>
{%- block html %}

<head>
  {%- block head %}
  <title>{% block title %}{{title|default}}{% endblock title %}</title>
  <link rel="icon" type="image/x-icon" href="{{ url_for('static', filename='images/icon.png') }}">
  {%- block metas %}
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta charset="utf-8">
  {%- endblock metas %}

  {%- block styles %}
  <link rel="stylesheet" href="{{ url_for('static', filename='css/base.css') }}" type="text/css">
  <!-- Bootstrap -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
  {%- endblock styles %}
  {%- endblock head %}
</head>

<body {% block body_attribs %}{% endblock body_attribs %}>
  {% block navbar %}

  <nav class="navbar navbar-expand-lg bg-body-secondary border-bottom border-black">
    <div class="container">
      <a class="navbar-brand text-yellow" href="#">
        <img src="{{ url_for('static', filename='images/icon.png') }}" alt="Logo" width="24" height="24"
          class="d-inline-block align-text-top text-yellow">
        The Hive
      </a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link {% if current_page == 'main.index' %}active{% endif %}"
              aria-current="{% if current_page == 'main.index' %}page{% endif %}"
              href="{{ url_for('main.index') }}">Home</a>
          </li>
          {% if current_user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('auth.logout') }}"> User: {{ current_user.username }}</a>
          </li>
          {% else %}
          <li class="nav-item">
            <a class="nav-link {% if current_page == 'auth.login' %}active{% endif %}"
              href="{{ url_for('auth.login') }}">Login</a>
          </li>
          {% endif %}
          <li class="nav-item">
            <a class="nav-link {% if current_page == 'auth.signup' %}active{% endif %}"
              href="{{ url_for('auth.signup') }}">Sign Up</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>
  {%- endblock navbar %}
  <div class="container mt-4 alert-width">
    {% for category, message in get_flashed_messages(with_categories=true) %}
    <div class="alert alert-{{ category }}" role="alert">{{ message|safe }}</div>
    {% endfor %}
  </div>
  <main class="container">
    {% block content -%}{%- endblock content %}
    {% block footer -%}
    <footer class="container text-center mt-3 mb-3 border-top border-dark-subtle">
      <small class="footer-font-size pb-0 mb-0"> &copy; 2024 <a class="link-underline link-underline-opacity-0"
          href="#">Evan Carlile</a> / <a class="link-underline link-underline-opacity-0"
          href="https://github.com/ecar33">GitHub</a></small>
    </footer>
    {% endblock footer %}
  </main>
  {% block scripts %}
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js"
    integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r"
    crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js"
    integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy"
    crossorigin="anonymous"></script>
  {%- endblock scripts %}
</body>
{%- endblock html %}

</html>
{% endblock doc -%}

hive/templates/index.html
{% extends "base.html" %}

{% block styles %}
{{ super() }}
<link rel="stylesheet" href="{{ url_for('static', filename='css/index.css') }}" type="text/css">

{% endblock styles %}

{% block content %}
    <div class="container header-container text-center justify-content-center mt-5 mb-4">
      <img src="{{ url_for('static', filename='images/icon.png') }}" class="img-fluid icon" alt="...">
      <h1 class="text-yellow header">The Hive</h1>
      <p class="header-subtitle text-dark-tertiary">leave a message</p>
    </div>
    <form method="POST", action="{{ url_for('message.post_message') }}">
      {{ form.hidden_tag() }}
      <div class="mb-3">
        {{ form.name.label(class_="fs-5") }}
        {{ form.name(class_="form-control form-control-lg") }}
      </div>
      <div class="mb-3">
        {{ form.body.label(class_="fs-5") }}
        {{ form.body(class_="form-control form-control-lg text-form") }}
      </div>
      <div class="mb-3">
        {{ form.submit(class_="btn btn-secondary mt-2 mb-2 btn-lg") }}
      </div>
    </form>

  <h3>{{ page.total }} Messages</h3>
  <ul class="list-group">
    {% for message in page.items %}
      <li class="list-group-item">
        <div class="container pt-4 pb-1">
          <h5 class="d-inline text-yellow">{{ message.name }}</h5> 
          <p class="d-inline">#{{ message.id }}</p>
          <p class="d-inline float-end">{{ get_timedelta_string(message) }} ago</p>
          <p class="fs-5">{{ message.body }}</p>
        </div>
      </li>
    {% endfor %}
  </ul>
    
  {{ macros.render_pagination(page, 'main.index') }}


{% endblock content%}

{% block scripts %}
{{ super() }}
{% endblock scripts%}

hive/templates/login.html
{% extends "base.html" %}

{% block content %}
<form method="POST">
    {{ form.csrf_token }}
    {{ form.username.label }}
    {{ form.username }}
    <br>
    <br>
    {{ form.password.label }}
    {{ form.password }}
    <br>
    <br>
    {{ form.submit }}
</form>
{% endblock content%}

hive/templates/macros.html
{% macro render_pagination(pagination, endpoint) %}
  <p class="mt-2 mb-1 container">
    {{ pagination.first }} - {{ pagination.last }} of {{ pagination.total }}
  </p>
  <nav>
    <ul class="pagination pagination-sm container justify-content-center d-xs-flex d-sm-flex d-md-none">
        <li class="page-item">
            <a class="page-link {% if not pagination.has_prev %}disabled{% endif %}" href="{{ url_for(endpoint, page=pagination.prev_num) }}">«</a>
        </li>
        {% for page in pagination.iter_pages() %}
        {% if page %}
            {% if page != pagination.page %}
            <li class="page-item">
                <a class="page-link" href="{{ url_for(endpoint, page=page) }}">{{ page }}</a>
            </li>
            {% else %}
            <li class="page-item active">
                <a class="page-link" href="{{ url_for(endpoint, page=page) }}">{{ page }}</a>
            </li>
            {% endif %}
        {% else %}
            <li class="page-item disabled">
                <a class="page-link" href="{{ url_for(endpoint, page=page) }}">…</a>
            </li>
        {% endif %}
        {% endfor %}
        <li class="page-item">
            <a class="page-link {% if not pagination.has_next %}disabled{% endif %}" href="{{ url_for(endpoint, page=pagination.next_num) }}">»</a>
        </li>
    </ul>
    <ul class="pagination container justify-content-center d-none d-md-flex d-lg-flex">
        <li class="page-item">
            <a class="page-link {% if not pagination.has_prev %}disabled{% endif %}" href="{{ url_for(endpoint, page=pagination.prev_num) }}">«</a>
        </li>
        {% for page in pagination.iter_pages() %}
        {% if page %}
            {% if page != pagination.page %}
            <li class="page-item">
                <a class="page-link" href="{{ url_for(endpoint, page=page) }}">{{ page }}</a>
            </li>
            {% else %}
            <li class="page-item active">
                <a class="page-link" href="{{ url_for(endpoint, page=page) }}">{{ page }}</a>
            </li>
            {% endif %}
        {% else %}
            <li class="page-item disabled">
                <a class="page-link" href="{{ url_for(endpoint, page=page) }}">…</a>
            </li>
        {% endif %}
        {% endfor %}
        <li class="page-item">
            <a class="page-link {% if not pagination.has_next %}disabled{% endif %}" href="{{ url_for(endpoint, page=pagination.next_num) }}">»</a>
        </li>
    </ul>
  </nav>
{% endmacro %}

hive/templates/signup.html
{% extends "base.html" %}

{% block content %}
{% for error in form.confirm_password.errors %}
  <div class="error">{{ error }}</div>
{% endfor %}

<form method="POST">
    {{ form.csrf_token }}
    {{ form.username.label }}
    {{ form.username }}
    <br>
    <br>
    {{ form.password.label }}
    {{ form.password }}
    <br>
    <br>
    {{ form.confirm_password.label }}
    {{ form.confirm_password }}
    <br>
    <br>
    {{ form.submit }}
</form>
{% endblock content%}